name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"
account_id = "20cf67bbae450d886a05a80800c32176"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "news-management"
database_id = "1b90b9b8-7e4d-49d9-9c0b-a6bec0b2c9cb"
